apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
        type: app
spec:
    containers:
        - name: java-app
          image: image_tag
    command:
      - sleep
      - "3600"  # Sleep for 1 hour to keep the pod running
